'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServiceCoordinacion
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceCoordinacion.ServicioCoordinacionSoap")>  _
    Public Interface ServicioCoordinacionSoap
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento miAsignatura del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/MediaDedicacionAlumnos", ReplyAction:="*")>  _
        Function MediaDedicacionAlumnos(ByVal request As ServiceCoordinacion.MediaDedicacionAlumnosRequest) As ServiceCoordinacion.MediaDedicacionAlumnosResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class MediaDedicacionAlumnosRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="MediaDedicacionAlumnos", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServiceCoordinacion.MediaDedicacionAlumnosRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceCoordinacion.MediaDedicacionAlumnosRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class MediaDedicacionAlumnosRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public miAsignatura As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal miAsignatura As String)
            MyBase.New
            Me.miAsignatura = miAsignatura
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class MediaDedicacionAlumnosResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="MediaDedicacionAlumnosResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServiceCoordinacion.MediaDedicacionAlumnosResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceCoordinacion.MediaDedicacionAlumnosResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class MediaDedicacionAlumnosResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public MediaDedicacionAlumnosResult As Double
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal MediaDedicacionAlumnosResult As Double)
            MyBase.New
            Me.MediaDedicacionAlumnosResult = MediaDedicacionAlumnosResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ServicioCoordinacionSoapChannel
        Inherits ServiceCoordinacion.ServicioCoordinacionSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ServicioCoordinacionSoapClient
        Inherits System.ServiceModel.ClientBase(Of ServiceCoordinacion.ServicioCoordinacionSoap)
        Implements ServiceCoordinacion.ServicioCoordinacionSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceCoordinacion_ServicioCoordinacionSoap_MediaDedicacionAlumnos(ByVal request As ServiceCoordinacion.MediaDedicacionAlumnosRequest) As ServiceCoordinacion.MediaDedicacionAlumnosResponse Implements ServiceCoordinacion.ServicioCoordinacionSoap.MediaDedicacionAlumnos
            Return MyBase.Channel.MediaDedicacionAlumnos(request)
        End Function
        
        Public Function MediaDedicacionAlumnos(ByVal miAsignatura As String) As Double
            Dim inValue As ServiceCoordinacion.MediaDedicacionAlumnosRequest = New ServiceCoordinacion.MediaDedicacionAlumnosRequest()
            inValue.Body = New ServiceCoordinacion.MediaDedicacionAlumnosRequestBody()
            inValue.Body.miAsignatura = miAsignatura
            Dim retVal As ServiceCoordinacion.MediaDedicacionAlumnosResponse = CType(Me,ServiceCoordinacion.ServicioCoordinacionSoap).MediaDedicacionAlumnos(inValue)
            Return retVal.Body.MediaDedicacionAlumnosResult
        End Function
    End Class
End Namespace
